#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# local_branch="$(git rev-parse --abbrev-ref HEAD)"
# valid_branch_regex="^([A-Z]{2,4}-[0-9]{1,4}|develop)$"
# error_message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

# if [[ ! $local_branch =~ $valid_branch_regex ]]
# then
#     echo "$error_message"
#     exit 1
# fi

yarn lint-staged
